Repository LachlanCourt/rainbowBot, pull requests merged in 2021-09, with the labels that each got.

#29 Add python requirements and example config
  README.md
  bot.py
  config.json.example
  requirements.txt
Labels: enhancement

#43 Allow multiple rolemenus
  bot.py
Labels: tech debt

#49 Start contribution guide
  README.md
  contribution guide.md
Labels: documentation

#52 Move functionality to cogs to tidy the place up a bit
  .gitignore
  bot.py
  cogs/FileHandler.py
  cogs/GlobalConfig.py
  cogs/MessageHandler.py
  cogs/Moderation.py
  cogs/RoleMenu.py
Labels: tech debt

#55 Send locked command anywhere
  bot.py
  cogs/Moderation.py
Labels: enhancement

#58 Add command line arguments
  Examples/config.example
  bot.py
  cogs/GlobalConfig.py
Labels: enhancement

#59 Add tasks cog and implment automatic channel locking based off a file
  .gitignore
  Examples/tasks.json
  README.md
  bot.py
  cogs/GlobalConfig.py
  cogs/Moderation.py
  cogs/Tasks.py
  cogs/helpers/_taskValidator.py
Labels: enhancement
